### ISSUE TITLE
Can't run mvn checkstyle:checkstyle

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Core#100]
The default checkstyle plugin fails to start when running `mvn checkstyle:checkstyle`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.14:checkstyle (default-cli) on project moodcat-core: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Unable to find suppressions file at location: configuration/checkstyle-suppressions.xml: Could not find resource 'configuration/checkstyle-suppressions.xml'
```

I can't find it in the report as well.
Fix in #93?

**Comment by pangguoming** [comment]
really easy way to disable this problem is giving -Dcheckstyle.skip=true as an argument in mvn command like this - See more at: http://ozkanpakdil.github.io/maven/2015/10/08/mvn-disable-checkstyle.html#sthash.NZIiRBgp.dpuf
