### ISSUE TITLE
Soundcloud api integration

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#12]
Let soundcloud serve a stream for a song using API calls with a token. Related to #11.

**Comment by JWGmeligMeyling** [comment]
Is this core or frontend or both? Because the logging in / streaming part can be used client side only, but we might want to extract some data from the API as well. @GijsWeterings

**Comment by JeremybellEU** [comment]
The original idea was that the soundcloud api would serve a stream, which was fetched by the core using the provided EEMCS data. Afaik the stream had a different ID than the actual song ID, but if that ain't true we have to look how we can integrate it with the soundplayer of @GijsWeterings .
