### ISSUE TITLE
Make points available (backend)

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Core#129]

**Comment by GijsWeterings** [comment]
@GET - localhost:8080/api/users/{id}/points -> returns integer value of points
@GET - localhost:8080/api/users/{id}/points?amount=X -> updates value, X defaults to 0

**Comment by GijsWeterings** [comment]
@Azkle is this an acceptable schema for you?

**Comment by Azkle** [comment]
Looks good, I think this will work.

**Comment by Azkle** [comment]
Only not sure how to get the id of the user, but I'll look into that.

**Comment by JWGmeligMeyling** [comment]
Why would we want to have an end point to award points? Isn't this guarded by the system?

**Comment by JeremybellEU** [comment]
I don't think POST-ing points is valid as it can indeed be misused, however the GET is reasonable. You only want to award points on the backend for example in the SongAPI.toclassify() call

**Comment by GijsWeterings** [comment]
Since security isn't a critical factor in this system (contextproject, not a live product), I would like to keep this endpoint open for testability purposes. I do agree this shouldn't be called by the system in everyday usage, but testing achievements for example may be easier this way.
