### ISSUE TITLE
Decide how to store song data

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#13]
We must decide how we want to store the song data we received from EEMCS and can receive from Souncloud.

**Comment by JWGmeligMeyling** [comment]
Some idea's:
- Relational database (Postgres)
- Non-relational database (MongoDb)
- Search engine driven databases (Elastic search, http://www.javacodegeeks.com/2013/04/getting-started-with-elasticsearch.html)
