### ISSUE TITLE
Create a reader for data of EEMCS

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#14]
Create a reader for the data delivered by EEMCS. Must be done after #13 has been decided.

**Comment by JWGmeligMeyling** [comment]
If it's JSON we can use the same `ObjectMapper` we use from Resteasy to read the files. We first have to create classes for the models (`BState` in this case), and then read it using:
```java
ObjectMapper mapper = new ObjectMapper();
InputStream inputStream = this.getClass().getResourceAsStream(path);
BState state = mapper.readValue(inputStream, BState.class);
```
