### ISSUE TITLE
[live] Server hangs after very first room merge

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Core#151]
Songs synchronize to the database every minute (when there are changes). In production, the server breaks after the very first persist, causing the room to "lock". The song wont play any further. This problem can not be reproduced locally on either H2 or Postgres, so we will have to look into the server logs. I would also suggest to drop-recreate the schema and run bulk insert again to ensure that the problem is not related to an older schema.

**Comment by JeremybellEU** [comment]
Let's do the schema changes tomorrow and run bulk insert to get feedback asap. We have to get this fixed before the demo of next week, but preferably before coming friday.

**Comment by JeremybellEU** [comment]
This has been fixed during the chat message polling.
