### ISSUE TITLE
Setup data mining library

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#16]
Import and setup the data mining library for learning algorithm

**Comment by JeremybellEU** [comment]
Succesfully set up the git submodule, however maven does not want to import the code that easily. We tried to use packaging pom with a module to the library, but it does not generate a deployable jar file anymore. If we would want to change packaging back to jar, the module should be imported differently.

An other possibility was specifying the dependency as system provided, however this will cause cross-platform issues due to '/' vs '\'.

Currently looking into other options, such as maven repository (but requires a Nexus account of someone else) or just copy-paste the code into a subfolder/package.

**Comment by JWGmeligMeyling** [comment]
Dang, it this would have been the nicest method, as it works out of the box for both developers and CI / Travis. However, Maven submodules are only allowed if the project packages to `pom`, and we want to package to `jar`. We have three options:

- Move the MoodCat core into a subproject (/subfolder), introduce a parent project that packages to `pom`, and set the git module in the root (which also is a submodule). In this case the moodcat core can resolve the dependency automatically and package to a jar file.
- Copy the library files to our source folders
- Release the library on a private Maven repository. We have one for Devhub (where also the JPacman is hosted). In the future you could also consider deploying your framework to the Maven Central Repository, however, it would take a few days to become publicly available.
