### ISSUE TITLE
Implement vote-to-skip

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Core#188]
Currently we only exclude future plays of this song.

**Comment by JeremybellEU** [comment]
Must be done after #27 and extra behaviour required in frontend.

**Comment by JWGmeligMeyling** [comment]
Ah I thought you wanted to use the vote down for this.

**Comment by JeremybellEU** [comment]
Ah vote down indicates a user does not see the song as a good fit to the room, but the user can still like the song. Therefore I think we should implement it as a new button. Plus: if a user likes a song, but doesn't want to hear it right now, he might also vote to skip.

**Comment by JWGmeligMeyling** [comment]
The users opinion on this is very vague. I think we should not make a distinction. A vote down means the user did not like the song, and we failed to give a proper suggestion for the room, *assuming* that songs of the same mood will generally fit *most* of the users in a room.
