### ISSUE TITLE
Store vote-down of a user

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me-Core#27]
Users must be able to vote-to-skip on songs. A user must have a map of songs to #vote-to-skips in order to use this information later for user bias.

**Comment by JWGmeligMeyling** [comment]
How useful is this information? The skip may be related to just the current mood, and not have a persistent character at all. When interpreting the listeners preference across moods, the chance of passing the same song twice should be relatively low.

I share your vision on possible enhancements for user based preference, but I think they are difficult to fit in the current room-based model and have a "could-have" character.
