### ISSUE TITLE
Only run integration tests on master

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#42]
Configure the integration tests to make sure they are only run when you are on master.

To deter unnecessary integration tests while working on your own features.

**Comment by JWGmeligMeyling** [comment]
It's not even a product enhancements. It's just a task. And I don't think that the time our integration tests run will ever exceed the delay you have with Travis anyway :P

**Comment by JeremybellEU** [comment]
After a chat we decided it will not be useful for us to configure as the benefits don't outweigh the cons.
