### ISSUE TITLE
Obtain test data for unit vector-predictor

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#48]
Search for songs everyone likes and cluster their features into a test data set in order to unit test the algorithm.

**Comment by Azkle** [comment]
high valence and high arousal => Reece Mastin - Good Night https://www.youtube.com/watch?v=alp_2_uBIUo
			         Pharrell Williams - Happy https://www.youtube.com/watch?v=y6Sxv-sUYtM 
low valence and high arousal => Nickelback - Edge Of A Revolution https://www.youtube.com/watch?v=IYnuSsM7tRw
			        Heideroosjes - Dan zal ik mijn bakkes houden https://www.youtube.com/watch?v=xlaUl1YIb5U 
			        
high valence low high arousal => Racoon - Young and Wise https://www.youtube.com/watch?v=zCo1tLHhniw
			         Joel Baker - Every vessel every vein https://www.youtube.com/watch?v=wsRdDQyhFCo
low valence and low rousal => Mad World - Gary Jules https://www.youtube.com/watch?v=4N3N1MlvVc4

**Comment by JWGmeligMeyling** [comment]
Reopened because we need an unit test for monday https://github.com/MoodCat/MoodCat.me-Core/issues/61
