### ISSUE TITLE
Implement the  r-tree

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#84]
Implement the r-tree to be scalable. Pair with @JWGmeligMeyling

**Comment by JeremybellEU** [comment]
This ticket can be started after #99 has been merged.

**Comment by JWGmeligMeyling** [comment]
#99 is not set to be merged, as it is only the start of #94. Since #94 has only been continued this day, I dont expect this issue to start this sprint if it's really blocked. Or it wasn't blocked at all even at the first day of the sprint ;)

**Comment by JeremybellEU** [comment]
Working version has a PR, however mvn site is currently a bit wonky. We are looking into possibilties to deploy the dependencies on devhub in order to solve these issues.
