### ISSUE TITLE
Improve room instance, continue songs, bind to API's

### ISSUE THREAD

**Issue by JWGmeligMeyling** [MoodCat/MoodCat.me-Core#94]

**Comment by JWGmeligMeyling** [comment]
Rebased.

**Comment by GijsWeterings** [comment]
Delayed due to demo effect

**Comment by Azkle** [comment]
To facilitate next song and to be clear of the contract,  I call '/api/rooms/{roomid}' and from that I call room.song. So,you should set the new song.
